project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "notes/**/*.qmd"
    - "!contribute/**"

website:
  title: "卒論準備のためのデータ分析ノート"
  navbar:
    right:
      - href: notes/index.qmd
        text: 講義ノート
  sidebar:
    style: docked
    search: true
    contents:
      - href: notes/index.qmd
        text: Home
      - section: Notes
        contents:
          - href: notes/sessions/session-01.qmd
            text: 第1回
          - href: notes/sessions/session-02.qmd
            text: 第2回
          - href: notes/sessions/session-03.qmd
            text: 第3回

format:
  html:
    toc: true
    number-sections: true
    theme: flatly
    css: assets/styles.css
    lang: ja

execute:
  echo: false
  warning: false
  message: false
